name: Deploy

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # https://github.com/marketplace/actions/deploy-to-heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"
        env:
          HD_JWT_SECRET: ${{secrets.JWT}}
          HD_SENDGRID_API_KEY: ${{secrets.SENDGRID}}
